# Generated by Django 5.0.7 on 2026-08-17 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payuee_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('stock_remaining', models.IntegerField(default=0)),
                ('stock_status', models.CharField(max_length=50)),
                ('vendor_id', models.IntegerField()),
                ('vendor_type', models.CharField(max_length=50)),
                ('product_url_id', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(default=0)),
                ('estimated_delivery', models.IntegerField(default=7)),
                ('featured', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('sales_count', models.IntegerField(default=0)),
                ('rating_avg', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='products_pr_categor_d33117_idx'), models.Index(fields=['vendor_id'], name='products_pr_vendor__753ff8_idx'), models.Index(fields=['selling_price'], name='products_pr_selling_ef1917_idx'), models.Index(fields=['featured'], name='products_pr_feature_bda4a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcache')),
            ],
            options={
                'unique_together': {('user', 'product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
